// Authorship and licence strings for CSOMS.
//
// These identify the SOFTWARE and its author. They are fixed and are not the
// same thing as the client branding in `app_settings` — the company name and
// logo each agency configures for itself. Both appear together: the client's
// name says whose data this is, these lines say whose software it is. Never
// substitute one for the other.
//
// CANONICAL COPY. `frontend/src/appBranding.js` mirrors it for the browser
// bundle, because the Vite root is `frontend/` and reaching outside it at
// build time is fragile. The two are asserted identical by a unit check, so
// editing one without the other fails rather than silently drifting.

const AUTHOR_NAME = "Jeffrey Montiano";
const COPYRIGHT_YEAR = "2026";
const APP_SHORT = "CSOMS";
const APP_FULL = "Central Security Operations Management System";

const DEVELOPED_BY = `Developed by ${AUTHOR_NAME}`;
const COPYRIGHT = `© ${COPYRIGHT_YEAR} ${AUTHOR_NAME}. All rights reserved.`;

// Login screen, under the app title — two separate lines.
const LOGIN_LINES = [DEVELOPED_BY, COPYRIGHT];

// Footer of every page in the app, beneath the client's confidential line.
const APP_FOOTER = `${APP_SHORT} · ${DEVELOPED_BY} · ${COPYRIGHT}`;

// About panel in System Settings.
const ABOUT_TEXT =
  `${APP_SHORT} (${APP_FULL}) — ${DEVELOPED_BY}. ${COPYRIGHT} ` +
  "This software is licensed, not sold. Unauthorized copying, distribution, or modification is prohibited.";

// Footer of every generated PDF. Sits ALONGSIDE the client's company name,
// never in place of it.
//
// Every character here is in the WinAnsi set PDFKit's built-in fonts encode:
// the middle dot is U+00B7 and the copyright sign U+00A9. A glyph outside it
// silently truncates to a different character — see pdfMoney.js for the peso
// sign that taught us this.
const PDF_FOOTER = `Generated by ${APP_SHORT} · ${DEVELOPED_BY} · © ${COPYRIGHT_YEAR} ${AUTHOR_NAME}`;

module.exports = {
  AUTHOR_NAME, COPYRIGHT_YEAR, APP_SHORT, APP_FULL,
  DEVELOPED_BY, COPYRIGHT, LOGIN_LINES, APP_FOOTER, ABOUT_TEXT, PDF_FOOTER,
};
