// Authorship and licence strings for CSOMS — browser copy.
//
// MIRROR of src/lib/appBranding.js, which is canonical. It lives here because
// the Vite root is `frontend/`, and importing across that boundary is fragile
// at build time. A unit check asserts the two files produce identical strings,
// so changing one without the other fails loudly instead of drifting.
//
// These identify the SOFTWARE and its author. They are NOT the client branding
// in `app_settings` — the company name and logo each agency configures. Both
// appear together; never substitute one for the other.

export const AUTHOR_NAME = "Jeffrey Montiano";
export const COPYRIGHT_YEAR = "2026";
export const APP_SHORT = "CSOMS";
export const APP_FULL = "Central Security Operations Management System";

export const DEVELOPED_BY = `Developed by ${AUTHOR_NAME}`;
export const COPYRIGHT = `© ${COPYRIGHT_YEAR} ${AUTHOR_NAME}. All rights reserved.`;

// Login screen, under the app title — two separate lines.
export const LOGIN_LINES = [DEVELOPED_BY, COPYRIGHT];

// Footer of every page, beneath the client's confidential line.
export const APP_FOOTER = `${APP_SHORT} · ${DEVELOPED_BY} · ${COPYRIGHT}`;

// About panel in System Settings.
export const ABOUT_TEXT =
  `${APP_SHORT} (${APP_FULL}) — ${DEVELOPED_BY}. ${COPYRIGHT} ` +
  "This software is licensed, not sold. Unauthorized copying, distribution, or modification is prohibited.";

export const PDF_FOOTER = `Generated by ${APP_SHORT} · ${DEVELOPED_BY} · © ${COPYRIGHT_YEAR} ${AUTHOR_NAME}`;
